### ISSUE TITLE
尝试构建时报错:  BuildError: [   +4 ms] Podfile missing

### ISSUE THREAD

**Issue by ByWaveSite** [chen08209/FlClash#13]
`BuildError: [   +4 ms] Podfile missing
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:169:7)
           #2      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:43:55)
           <asynchronous suspension>
           #3      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:102:3)
           <asynchronous suspension>
           #4      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:158:27)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

Unhandled exception:
BuildError: [   +4 ms] Podfile missing
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:169:7)
           #2      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:43:55)
           <asynchronous suspension>
           #3      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:102:3)
           <asynchronous suspension>
           #4      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:158:27)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>`

请问如何解决

**Comment by ByWaveSite** [comment]
这个问题解决了, 现在卡在CodeSign报错, 以下是日志

```
[   +5 ms] Build process failed

[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:166:5)
           <asynchronous suspension>
           #2      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>



[  +60 ms] ensureAnalyticsSent: 60ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete

[ +119 ms] exiting with code 1

BuildError: [ +172 ms] --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[        ] { platform:macOS, arch:arm64, id:00006021-001251590E47401E, name:My Mac }
[        ] { platform:macOS, arch:x86_64, id:00006021-001251590E47401E, name:My Mac }
[  +10 ms] ** BUILD FAILED **
[        ] The following build commands failed:
[        ]      CodeSign /Users/nil/Desktop/ByWave/fl_clash/build/macos/Build/Products/Release/FlClash.app (in target 'Runner' from project 'Runner')
[        ] (1 failure)
[   +5 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:166:5)
           <asynchronous suspension>
           #2      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>




#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:158:27)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>


Unhandled exception:
BuildError: [ +172 ms] --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[        ] { platform:macOS, arch:arm64, id:00006021-001251590E47401E, name:My Mac }
[        ] { platform:macOS, arch:x86_64, id:00006021-001251590E47401E, name:My Mac }
[  +10 ms] ** BUILD FAILED **
[        ] The following build commands failed:
[        ]      CodeSign /Users/nil/Desktop/ByWave/fl_clash/build/macos/Build/Products/Release/FlClash.app (in target 'Runner' from project 'Runner')
[        ] (1 failure)
[   +5 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:166:5)
           <asynchronous suspension>
           #2      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>



#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:158:27)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```
