### ISSUE TITLE
Failed to clone 'core/Clash.Meta' a second time, aborting

### ISSUE THREAD

**Issue by wfs498121294** [chen08209/FlClash#255]
Failed to clone 'core/Clash.Meta' a second time, aborting
![image](https://github.com/user-attachments/assets/d5f7706b-d29c-4c61-9ac3-2fe4fb236fbd)

**Comment by wfs498121294** [comment]
dart setup.dart macos
run build libclash
go: downloading golang.org/x/net v0.25.0

common.go:5:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:6:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:7:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:8:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
log.go:6:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
hub.go:14:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
hub.go:15:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:9:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
hub.go:16:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:10:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:11:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:12:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
hub.go:19:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:13:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:14:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:15:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:16:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:17:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
hub.go:22:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
common.go:18:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
hub.go:24:2: github.com/3andne/restls-client-go@v0.1.6: Get "https://proxy.golang.org/github.com/3andne/restls-client-go/@v/v0.1.6.mod": dial tcp 142.251.211.241:443: i/o timeout
hub.go:25:2: golang.org/x/net@v0.25.0: Get "https://proxy.golang.org/golang.org/x/net/@v/v0.25.0.zip": dial tcp 142.250.217.113:443: i/o timeout

Unhandled exception:
build libclash error
#0      Build.exec (file:///Users/wanbiao/Downloads/FlClash-0.8.35/setup.dart:143:40)
<asynchronous suspension>
#1      Build.buildLib (file:///Users/wanbiao/Downloads/FlClash-0.8.35/setup.dart:181:7)
<asynchronous suspension>
#2      BuildCommand._buildLib (file:///Users/wanbiao/Downloads/FlClash-0.8.35/setup.dart:274:5)
<asynchronous suspension>
#3      BuildCommand.run (file:///Users/wanbiao/Downloads/FlClash-0.8.35/setup.dart:340:5)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

试了很多次  开了vpn 也还是这样

**Comment by wfs498121294** [comment]
总算自己搞定了
